### ISSUE TITLE
Wrong output data in environment

### ISSUE THREAD

**Issue by aleksey-svetliskiy-cere** [Tracking-Detector/docker-compose-builder#1]
please check Docker documentation https://docs.docker.com/compose/compose-file/05-services/#environment
there are two variants:
1. Map syntax:
```
environment:
  RACK_ENV: development
  SHOW: "true"
  USER_INPUT:
```
or
2. Array syntax:
```
environment:
  - RACK_ENV=development
  - SHOW=true
  - USER_INPUT
 ```

but actually this package generate it in format like
```
environment:
  - RACK_ENV: development
  - SHOW: "true"
  - USER_INPUT:
```
